### PR TITLE
Added support for dark theme

### PR DESCRIPTION
**Pull request by zakaryus**
I have never done a pull request before, so let me know if I'm doing something wrong here. This calendar is working great for me, but I needed it with a dark theme.

### CODE REVIEW

**Comment by AppleEducate** [comment]
I needed this too!
screen shot 2018-12-11 at 12 49 22 pm
screen shot 2018-12-11 at 12 49 10 pm

**Comment by AppleEducate** [comment]
Does your pull request support dark and black?

**Comment by AppleEducate** [comment]
Fixes: https://github.com/apptreesoftware/flutter_calendar/issues/41

**Comment by zakaryus** [comment]
Here's how it looks for me after my change. I also had to set theme primaryColor: Colors.purple, instead of primaryColorSwatch: Colors.purple, in order to get the selector to change color. Otherwise it always looked black.

with `primaryColor: Colors.purple`
flutter_calendar_preview

with `primaryColorSwatch: Colors.purple`
flutter_calendar_after

**Comment by AppleEducate** [comment]
Looks great!! Thanks for the work

**Review by ericwindmill — APPROVED** [review]
Thanks, everyone. I'll publish this as soon as I can.

**Comment by rodydavis** [comment]
The theme is broken again on dark mode? Was this overwritten?

**Pull request merged**
